<!DOCTYPE school
[<!ELEMENT school (school_name, fullname, location, faculties+)>
<!ELEMENT school_name (#PCDATA)>
<!ELEMENT fullname (#PCDATA)>
<!ELEMENT location (country+, city+, address+)>
<!ELEMENT city (#PCDATA)>
<!ATTLIST city zip CDATA #REQUIRED>
<!ELEMENT country (#PCDATA)>
<!ELEMENT address (#PCDATA)>

<!ELEMENT faculties (faculty+)>
<!ELEMENT faculty (f_name+, katedry*)>
<!ELEMENT f_name (#PCDATA)>
<!ATTLIST f_name  shortcut CDATA #REQUIRED>

<!ELEMENT katedry (katedra+)>
<!ELEMENT katedra (k_name+,lektor?,teachers?,students?)>
<!ELEMENT k_name (#PCDATA)>
<!ATTLIST k_name dekan CDATA #IMPLIED>
<!ELEMENT lektor (#PCDATA)>

<!ELEMENT teachers (teacher*)>
<!ELEMENT teacher (t_name*,(t_telefon|t_email),pozice+)>
<!ELEMENT t_name (#PCDATA)>
<!ELEMENT t_telefon (#PCDATA)>
<!ELEMENT t_email (#PCDATA)>
<!ELEMENT pozice (#PCDATA)>

<!ELEMENT students (student*)>
<!ELEMENT student (s_name+,st+,s_email*)>
<!ELEMENT s_name (#PCDATA)>
<!ELEMENT st (#PCDATA)>
<!ELEMENT s_email (#PCDATA)>
]>

<school>
    <school_name>UJEP</school_name>
    <fullname>Univerzita Jana Evangelisty Purkyně v Ústí nad Labem</fullname>
    <location>
        <country>Česká republika</country>
        <city zip="40096">Ústí nad Labem</city>
        <address>Pasteurova 3544/1</address>
    </location>
    <faculties>
        <faculty>
            <f_name shortcut="FSI">Fakulta strojního inženýrství</f_name>
        </faculty>
        <faculty>
            <f_name shortcut="FZP">Fakulta životního prostředí</f_name>
        </faculty>
        <faculty>
            <f_name shortcut="FUD">Fakulta umění a designu</f_name>
        </faculty>
        <faculty>
            <f_name shortcut="FF">Filozofická fakulta</f_name>
        </faculty>
        <faculty>
            <f_name shortcut="FZS">Fakulta zdravotních studií</f_name>
        </faculty>	
        <faculty>
            <f_name shortcut="FAV">Přírodovědecká fakulta</f_name>
            <katedry>
                <katedra>
                    <k_name>Katedra biologie</k_name>
                </katedra>
                <katedra>
                    <k_name>Katedra fyziky</k_name>
                </katedra>
                <katedra>
                    <k_name>Katedra geografie</k_name>
                </katedra>
                <katedra>
                    <k_name>Katedra chemie</k_name>
                </katedra>
                <katedra>
                    <k_name>Katedra informatiky</k_name>
                </katedra>
                <katedra>
                    <k_name dekan="Michal Varady">Katedra matematiky</k_name>
                    <lektor></lektor>
                    <teachers>
                        <teacher>
                            <t_name>Pavel Beránek</t_name>
                            <t_telefon>00000000</t_telefon>
                            <pozice>specialista</pozice>
                        </teacher>
                        <teacher>
                            <t_name>Jiří Škvor</t_name>
                            <t_telefon>000000</t_telefon>
                            <pozice>vedoucí katedry</pozice>
                        </teacher>
                    </teachers>
                    <students>
                        <student>
                            <s_name>Matěj Kaška</s_name>
                            <st>st96116</st>
                            <s_email>nkaskaj@gmail.com</s_email>
                        </student>
                        <student>
                            <s_name>Jan Chlouba</s_name>
                            <st>st81555</st>
                            <s_email>chlouba@gmail.com</s_email>
                        </student>
                        <student>
                            <s_name>Jakub Moravec</s_name>
                            <st>st516516</st>
                            <s_email>moravec@gmail.com</s_email>
                        </student>
                    </students>
                </katedra>
            </katedry>
        </faculty>
        <faculty>
            <f_name shortcut="PF">Pedagogická fakulta</f_name>
        </faculty>
        <faculty>
            <f_name shortcut="FSE">Fakulta sociálně ekonomická</f_name>
        </faculty>
    </faculties>
</school>